// PCG32 PRNG WASM binary (embedded as base64 to avoid filesystem path issues in production)
const PCG_WASM_B64 =
    'AGFzbQEAAAABLAhgAX8Bf2AAAGAFf39/f38Bf2ABfwBgA398fAF8YAF/AXxgAAF/YAJ+fgF/Ag0C' +
    'AWEBYQABAWEBYgAAAw4NAAAEAgIFAAMGAAMHAQQFAXABAQEFBwEBggKAgAIGCAF/AUGAjAQLBzUN' +
    'AWMCAAFkAA4BZQANAWYACQFnAAgBaAAHAWkABgFqAAUBawAEAWwAAwFtAAwBbgALAW8ACgwBAQqA' +
    'MQ1UAgF/AX4CQEGACCgCACIBrSAArUIHfEL4////H4N8IgJC/////w9YBEAgAqciAD8AQRB0TQ0B' +
    'IAAQAQ0BC0GECEEwNgIAQX8PC0GACCAANgIAIAELOAEBfiAAIAApAwggACkDACIBQq3+1eTUhf2o' +
    '2AB+fDcDACABQi2IIAFCG4iFpyABQjuIp3hBH3YLWgEBfiAAIAApAwggACkDACIDQq3+1eTUhf2o' +
    '2AB+fDcDACABIAIgASACZCIAGyACIAEgABsiAaEgA0ItiCADQhuIhacgA0I7iKd4uEQAAAAAAADw' +
    'PaKiIAGgC8kBAQV+IAEgAiABIAJLGyAEQQFzayIEIANBAXMgASACIAEgAkkbaiIDTwR/IAApAwgh' +
    'BiAEIANrIgJBAWoiAUUEQCAAIAApAwAiBUKt/tXk1IX9qNgAfiAGfDcDACAFQi2IIAVCG4iFpyAF' +
    'QjuIp3gPCyACQX9zIAFwIQIgACkDACEFA0AgBUIbiCAFQi2IIAVCO4ghCSAFQq3+1eTUhf2o2AB+' +
    'IAZ8IQWFpyAJp3giBCACSQ0ACyAAIAU3AwAgBCABcCADagUgAwsLzwECAX8FfiABIAIgASACSBsh' +
    'BQJ/IANFBEBB/////wcgBUH/////B0YNARogBUEBaiEFCyABIAIgASACShshAiAERQRAQYCAgIB4' +
    'IAJBgICAgHhGDQEaIAJBAWshAgsgAiAFSARAIAUPCyACIAVrIgFBf3MgAUEBaiIBcCECIAApAwAh' +
    'BiAAKQMIIQcDQCAGQhuIIAZCLYggBkI7iCEKIAZCrf7V5NSF/ajYAH4gB3whBoWnIAqneCIDIAJJ' +
    'DQALIAAgBjcDACADIAFwIAVqCwtAAQF+IAAgACkDCCAAKQMAIgFCrf7V5NSF/ajYAH58NwMAIAFC' +
    'LYggAUIbiIWnIAFCO4ineLhEAAAAAAAA8D2iCzUBAX4gACAAKQMIIAApAwAiAUKt/tXk1IX9qNgA' +
    'fnw3AwAgAUItiCABQhuIhacgAUI7iKd4C+kLAQh/IAAEQAJAIABFDQAgAEEIayICIABBBGsoAgAi' +
    'AEF4cSIEaiEFAkAgAEEBcQ0AIABBAnFFDQEgAiACKAIAIgBrIgJBmAgoAgBJDQEgACAEaiEEAkAC' +
    'QAJAQZwIKAIAIAJHBEAgAigCDCEBIABB/wFNBEAgASACKAIIIgNHDQJBiAhBiAgoAgBBfiAAQQN2' +
    'd3E2AgAMBQsgAigCGCEGIAEgAkcEQCACKAIIIgAgATYCDCABIAA2AggMBAsgAigCFCIABH8gAkEU' +
    'agUgAigCECIARQ0DIAJBEGoLIQMDQCADIQcgACIBQRRqIQMgASgCFCIADQAgAUEQaiEDIAEoAhAi' +
    'AA0ACyAHQQA2AgAMAwsgBSgCBCIAQQNxQQNHDQNBkAggBDYCACAFIABBfnE2AgQgAiAEQQFyNgIE' +
    'IAUgBDYCAAwECyADIAE2AgwgASADNgIIDAILQQAhAQsgBkUNAAJAIAIoAhwiAEECdCIDKAK4CiAC' +
    'RgRAIANBuApqIAE2AgAgAQ0BQYwIQYwIKAIAQX4gAHdxNgIADAILAkAgAiAGKAIQRgRAIAYgATYC' +
    'EAwBCyAGIAE2AhQLIAFFDQELIAEgBjYCGCACKAIQIgAEQCABIAA2AhAgACABNgIYCyACKAIUIgBF' +
    'DQAgASAANgIUIAAgATYCGAsgAiAFTw0AIAUoAgQiAEEBcUUNAAJAAkACQAJAIABBAnFFBEBBoAgo' +
    'AgAgBUYEQEGgCCACNgIAQZQIQZQIKAIAIARqIgA2AgAgAiAAQQFyNgIEIAJBnAgoAgBHDQZBkAhB' +
    'ADYCAEGcCEEANgIADAYLQZwIKAIAIgggBUYEQEGcCCACNgIAQZAIQZAIKAIAIARqIgA2AgAgAiAA' +
    'QQFyNgIEIAAgAmogADYCAAwGCyAAQXhxIARqIQQgBSgCDCEBIABB/wFNBEAgBSgCCCIDIAFGBEBB' +
    'iAhBiAgoAgBBfiAAQQN2d3E2AgAMBQsgAyABNgIMIAEgAzYCCAwECyAFKAIYIQYgASAFRwRAIAUo' +
    'AggiACABNgIMIAEgADYCCAwDCyAFKAIUIgAEfyAFQRRqBSAFKAIQIgBFDQIgBUEQagshAwNAIAMh' +
    'ByAAIgFBFGohAyABKAIUIgANACABQRBqIQMgASgCECIADQALIAdBADYCAAwCCyAFIABBfnE2AgQg' +
    'AiAEQQFyNgIEIAIgBGogBDYCAAwDC0EAIQELIAZFDQACQCAFKAIcIgBBAnQiAygCuAogBUYEQCAD' +
    'QbgKaiABNgIAIAENAUGMCEGMCCgCAEF+IAB3cTYCAAwCCwJAIAUgBigCEEYEQCAGIAE2AhAMAQsg' +
    'BiABNgIUCyABRQ0BCyABIAY2AhggBSgCECIABEAgASAANgIQIAAgATYCGAsgBSgCFCIARQ0AIAEg' +
    'ADYCFCAAIAE2AhgLIAIgBEEBcjYCBCACIARqIAQ2AgAgAiAIRw0AQZAIIAQ2AgAMAQsgBEH/AU0E' +
    'QCAEQfgBcUGwCGohAAJ/QYgIKAIAIgNBASAEQQN2dCIBcUUEQEGICCABIANyNgIAIAAMAQsgACgC' +
    'CAshAyAAIAI2AgggAyACNgIMIAIgADYCDCACIAM2AggMAQtBHyEBIARB////B00EQCAEQSYgBEEI' +
    'dmciAGt2QQFxIABBAXRrQT5qIQELIAIgATYCHCACQgA3AhAgAUECdEG4CmohAwJ/AkACf0GMCCgC' +
    'ACIAQQEgAXQiB3FFBEBBjAggACAHcjYCACADIAI2AgBBGCEBQQgMAQsgBEEZIAFBAXZrQQAgAUEf' +
    'Rxt0IQEgAygCACEDA0AgAyIAKAIEQXhxIARGDQIgAUEddiEDIAFBAXQhASAAIANBBHFqIgcoAhAi' +
    'Aw0ACyAHIAI2AhBBGCEBIAAhA0EICyEEIAIiAAwBCyAAKAIIIgMgAjYCDCAAIAI2AghBGCEEQQgh' +
    'AUEACyEHIAEgAmogAzYCACACIAA2AgwgAiAEaiAHNgIAQagIQagIKAIAQQFrIgBBfyAAGzYCAAsL' +
    'CwQAIwALEAAjACAAa0FwcSIAJAAgAAsGACAAJAAL9h4BC38DQAJAQQAhAkEAIQQjAEEQayIMJAAC' +
    'QEGICCgCACIHQQN2IgNBA3EEQAJAIANBf3NBAXFBA2oiA0EDdCIGQbAIaiIEIAYoArgIIgUoAggi' +
    'AkYEQEGICCAHQX4gA3dxNgIADAELIAIgBDYCDCAEIAI2AggLIAVBCGohAiAFIAZBA3I2AgQgBSAG' +
    'aiIDIAMoAgRBAXI2AgQMAQsCQAJAAkACQAJAAkACQEGQCCgCACIJQRhPDQAgAwRAAkAgA0EDdEFw' +
    'cWgiA0EDdCIGQbAIaiIEIAYoArgIIgsoAggiAkYEQEGICCAHQX4gA3dxIgc2AgAMAQsgAiAENgIM' +
    'IAQgAjYCCAsgC0EbNgIEIAtBGGoiBCAGQRhrIgVBAXI2AgQgBiALaiAFNgIAIAkEQCAJQXhxQbAI' +
    'aiEGQZwIKAIAIQICfyAHQQEgCUEDdnQiA3FFBEBBiAggAyAHcjYCACAGDAELIAYoAggLIQMgBiAC' +
    'NgIIIAMgAjYCDCACIAY2AgwgAiADNgIICyALQQhqIQJBnAggBDYCAEGQCCAFNgIADAgLQYwIKAIA' +
    'IgtFDQAgC2hBAnQoArgKIgQoAgRBeHFBGGshCCAEIQMDQAJAIAMoAhAiAkUEQCADKAIUIgJFDQEL' +
    'IAIoAgRBeHFBGGsiAyAIIAMgCEkiAxshCCACIAQgAxshBCACIQMMAQsLIAQoAhghCiAEIAQoAgwi' +
    'AkcEQCAEKAIIIgMgAjYCDCACIAM2AggMBwsgBCgCFCIDBH8gBEEUagUgBCgCECIDRQ0CIARBEGoL' +
    'IQUDQCAFIQYgAyICQRRqIQUgAigCFCIDDQAgAkEQaiEFIAIoAhAiAw0ACyAGQQA2AgAMBgtBkAgo' +
    'AgAiBUEYTwRAQZwIKAIAIQICQCAFQRhrIgNBEE8EQCACQRhqIgQgA0EBcjYCBCACIAVqIAM2AgAg' +
    'AkEbNgIEDAELIAIgBUEDcjYCBCACIAVqIgMgAygCBEEBcjYCBEEAIQMLQZAIIAM2AgBBnAggBDYC' +
    'ACACQQhqIQIMBwtBlAgoAgAiCkEYSwRAQZQIIApBGGsiAzYCAEGgCEGgCCgCACICQRhqNgIAIAIg' +
    'A0EBcjYCHCACQRs2AgQgAkEIaiECDAcLAn9B4AsoAgAEQEHoCygCAAwBC0HsC0J/NwIAQeQLQoCg' +
    'gICAgAQ3AgBB4AsgDEEMakFwcUHYqtWqBXM2AgBB9AtBADYCAEHEC0EANgIAQYAgCyIDQccAaiIL' +
    'QQAgA2siB3EiA0EYTQ0GQcALKAIAIgYEQEG4CygCACIFIANqIgQgBU0NByAEIAZLDQcLAkBBxAst' +
    'AABBBHFFBEACQAJAAkACQEGgCCgCACIFBEBByAshAgNAIAIoAgAiBCAFTQRAIAUgBCACKAIEakkN' +
    'AwsgAigCCCICDQALC0EAEAIiBEF/Rg0DIAMhB0HkCygCACIFQQFrIgIgBHEEQCADIARrIAIgBGpB' +
    'ACAFa3FqIQcLIAdBGE0NA0HACygCACIGBEBBuAsoAgAiBSAHaiICIAVNDQQgAiAGSw0ECyAHEAIi' +
    'AiAERw0BDAULIAsgCmsgB3EiBxACIgQgAigCACACKAIEakYNASAEIQILIAJBf0YNASAHQcgATwRA' +
    'IAIhBAwEC0HoCygCACIEQccAIAdrakEAIARrcSIEEAJBf0YNASAEIAdqIQcgAiEEDAMLIARBf0cN' +
    'AgtBxAtBxAsoAgBBBHI2AgALIAMQAiEEQQAQAiEDIARBf0YNBCADQX9GDQQgAyAETQ0EIAMgBGsi' +
    'B0HAAE0NBAtBuAtBuAsoAgAgB2oiAzYCAEG8CygCACADSQRAQbwLIAM2AgALAkBBoAgoAgAiBgRA' +
    'QcgLIQIDQCAEIAIoAgAiBSACKAIEIgNqRg0CIAIoAggiAg0ACwwDC0GYCCgCACIDQQAgAyAETRtF' +
    'BEBBmAggBDYCAAtBACECQcwLIAc2AgBByAsgBDYCAEGoCEF/NgIAQawIQeALKAIANgIAQdQLQQA2' +
    'AgADQCACQQN0IgUgBUGwCGoiAzYCuAggBSADNgK8CCACQQFqIgJBIEcNAAtBlAggB0EoayIFQXgg' +
    'BGtBB3EiA2siAjYCAEGgCCADIARqIgM2AgAgAyACQQFyNgIEIAQgBWpBKDYCBEGkCEHwCygCADYC' +
    'AAwDCyAEIAZNDQEgBSAGSw0BIAIoAgxBCHENASACIAMgB2o2AgRBoAggBkF4IAZrQQdxIgNqIgQ2' +
    'AgBBlAhBlAgoAgAgB2oiAiADayIDNgIAIAQgA0EBcjYCBCACIAZqQSg2AgRBpAhB8AsoAgA2AgAM' +
    'AgtBACECDAQLQZgIKAIAIARLBEBBmAggBDYCAAsgBCAHaiEDQcgLIQICQANAIAMgAigCACIFRwRA' +
    'IAIoAggiAg0BDAILCyACLQAMQQhxRQ0DC0HICyECA0ACQCACKAIAIgMgBk0EQCAGIAMgAigCBGoi' +
    'C0kNAQsgAigCCCECDAELC0GUCCAHQShrIgVBeCAEa0EHcSIDayICNgIAQaAIIAMgBGoiAzYCACAD' +
    'IAJBAXI2AgQgBCAFakEoNgIEQaQIQfALKAIANgIAIAYgC0EnIAtrQQdxakEvayIDIAMgBkEQakkb' +
    'IgVBGzYCBCAFQdALKQIANwIQIAVByAspAgA3AghB0AsgBUEIajYCAEHMCyAHNgIAQcgLIAQ2AgBB' +
    '1AtBADYCACAFQRhqIQIDQCACQQc2AgQgAkEIaiACQQRqIQIgC0kNAAsgBSAGRg0AIAUgBSgCBEF+' +
    'cTYCBCAGIAUgBmsiB0EBcjYCBCAFIAc2AgACfyAHQf8BTQRAIAdB+AFxQbAIaiECAn9BiAgoAgAi' +
    'BEEBIAdBA3Z0IgNxRQRAQYgIIAMgBHI2AgAgAgwBCyACKAIICyEDIAIgBjYCCCADIAY2AgxBDCEE' +
    'QQgMAQtBHyECIAdB////B00EQCAHQSYgB0EIdmciA2t2QQFxIANBAXRrQT5qIQILIAYgAjYCHCAG' +
    'QgA3AhAgAkECdEG4CmohAwJAAkBBjAgoAgAiBUEBIAJ0IgRxRQRAQYwIIAQgBXI2AgAgAyAGNgIA' +
    'DAELIAdBGSACQQF2a0EAIAJBH0cbdCECIAMoAgAhBQNAIAUiAygCBEF4cSAHRg0CIAJBHXYhBCAC' +
    'QQF0IQIgAyAEQQRxaiIEKAIQIgUNAAsgBCAGNgIQCyAGIAM2AhhBCCEEIAYiAyECQQwMAQsgAygC' +
    'CCICIAY2AgwgAyAGNgIIIAYgAjYCCEEAIQJBGCEEQQwLIAZqIAM2AgAgBCAGaiACNgIAC0GUCCgC' +
    'ACIDQRhNDQBBlAggA0EYayIDNgIAQaAIQaAIKAIAIgJBGGo2AgAgAiADQQFyNgIcIAJBGzYCBCAC' +
    'QQhqIQIMAwtBhAhBMDYCAEEAIQIMAgsgAiAENgIAIAIgAigCBCAHajYCBCAEQXggBGtBB3FqIgdB' +
    'GzYCBCAFQXggBWtBB3FqIgkgB0EYaiIIayEKAkBBoAgoAgAgCUYEQEGgCCAINgIAQZQIQZQIKAIA' +
    'IApqIgM2AgAgCCADQQFyNgIEDAELQZwIKAIAIAlGBEBBnAggCDYCAEGQCEGQCCgCACAKaiIDNgIA' +
    'IAggA0EBcjYCBCADIAhqIAM2AgAMAQsgCSgCBCICQQNxQQFGBEAgAkF4cSEGIAkoAgwhBQJAIAJB' +
    '/wFNBEAgCSgCCCIDIAVGBEBBiAhBiAgoAgBBfiACQQN2d3E2AgAMAgsgAyAFNgIMIAUgAzYCCAwB' +
    'CyAJKAIYIQsCQCAFIAlHBEAgCSgCCCIDIAU2AgwgBSADNgIIDAELAkAgCSgCFCICBH8gCUEUagUg' +
    'CSgCECICRQ0BIAlBEGoLIQMDQCADIQQgAiIFQRRqIQMgAigCFCICDQAgBUEQaiEDIAUoAhAiAg0A' +
    'CyAEQQA2AgAMAQtBACEFCyALRQ0AAkAgCSgCHCICQQJ0IgMoArgKIAlGBEAgA0G4CmogBTYCACAF' +
    'DQFBjAhBjAgoAgBBfiACd3E2AgAMAgsCQCAJIAsoAhBGBEAgCyAFNgIQDAELIAsgBTYCFAsgBUUN' +
    'AQsgBSALNgIYIAkoAhAiAwRAIAUgAzYCECADIAU2AhgLIAkoAhQiA0UNACAFIAM2AhQgAyAFNgIY' +
    'CyAGIApqIQogBiAJaiIJKAIEIQILIAkgAkF+cTYCBCAIIApBAXI2AgQgCCAKaiAKNgIAIApB/wFN' +
    'BEAgCkH4AXFBsAhqIQQCf0GICCgCACICQQEgCkEDdnQiA3FFBEBBiAggAiADcjYCACAEDAELIAQo' +
    'AggLIQMgBCAINgIIIAMgCDYCDCAIIAQ2AgwgCCADNgIIDAELQR8hBSAKQf///wdNBEAgCkEmIApB' +
    'CHZnIgNrdkEBcSADQQF0a0E+aiEFCyAIIAU2AhwgCEIANwIQIAVBAnRBuApqIQICQAJAQYwIKAIA' +
    'IgRBASAFdCIDcUUEQEGMCCADIARyNgIAIAIgCDYCAAwBCyAKQRkgBUEBdmtBACAFQR9HG3QhBSAC' +
    'KAIAIQMDQCADIgIoAgRBeHEgCkYNAiAFQR12IQMgBUEBdCEFIAIgA0EEcWoiBCgCECIDDQALIAQg' +
    'CDYCEAsgCCACNgIYIAggCDYCDCAIIAg2AggMAQsgAigCCCIDIAg2AgwgAiAINgIIIAhBADYCGCAI' +
    'IAI2AgwgCCADNgIICyAHQQhqIQIMAQsCQCAKRQ0AAkAgBCgCHCIFQQJ0IgMoArgKIARGBEAgA0G4' +
    'CmogAjYCACACDQFBjAggC0F+IAV3cTYCAAwCCwJAIAQgCigCEEYEQCAKIAI2AhAMAQsgCiACNgIU' +
    'CyACRQ0BCyACIAo2AhggBCgCECIDBEAgAiADNgIQIAMgAjYCGAsgBCgCFCIDRQ0AIAIgAzYCFCAD' +
    'IAI2AhgLAkAgCEEPTQRAIAQgCEEYaiIDQQNyNgIEIAMgBGoiAyADKAIEQQFyNgIEDAELIARBGzYC' +
    'BCAEQRhqIgIgCEEBcjYCBCACIAhqIAg2AgAgCQRAIAlBeHFBsAhqIQZBnAgoAgAhBQJ/QQEgCUED' +
    'dnQiAyAHcUUEQEGICCADIAdyNgIAIAYMAQsgBigCCAshAyAGIAU2AgggAyAFNgIMIAUgBjYCDCAF' +
    'IAM2AggLQZwIIAI2AgBBkAggCDYCAAsgBEEIaiECCyAMQRBqJAAgAg0AQfgLKAIAIgNFDQAgAxEB' +
    'AAwBCwsgAkUEQBAAAAsgAiABQgGGQgGEIgE3AwggAiAAIAF8Qq3+1eTUhf2o2AB+IAF8NwMAIAIL' +
    'AgALCwkBAEGBCAsCBgE=';

// -- WASM export map (from emscripten-compiled pcg_rng.wasm) --

interface PcgWasmExports {
    c: WebAssembly.Memory;       // memory
    d: () => void;               // __init_runtime
    e: (seed: bigint, seq: bigint) => number;  // pcg_create
    f: (rng: number) => void;    // pcg_destroy
    g: (rng: number) => number;  // pcg32
    h: (rng: number) => number;  // pcg_normalized
    i: (rng: number, min: number, max: number, incMin: number, incMax: number) => number; // pcg_between
    j: (rng: number, min: number, max: number, incMin: number, incMax: number) => number; // pcg_between_u32
    k: (rng: number, min: number, max: number) => number; // pcg_between_float
    l: (rng: number) => number;  // pcg_bool
}

/** High-level PCG32 PRNG wrapper backed by WebAssembly. */
export interface PcgRng {
    /** Random float in [0, 1) -- drop-in replacement for Math.random(). */
    random(): number;
    /** Random integer in [min, max] (inclusive both ends). */
    between(min: number, max: number): number;
    /** Free the WASM-allocated RNG instance. */
    destroy(): void;
}

let wasmExports: PcgWasmExports | null = null;

async function loadWasm(): Promise<PcgWasmExports> {
    if (wasmExports) return wasmExports;

    const wasmBuffer = Buffer.from(PCG_WASM_B64, 'base64');

    const importObject = {
        a: {
            a: () => { throw new Error('PCG WASM abort'); },
            b: (requested: number) => {
                const memory = wasmExports?.c;
                if (!memory) return 0;
                const pages = Math.ceil((requested - memory.buffer.byteLength + 65535) / 65536);
                try { memory.grow(pages); return 1; } catch { return 0; }
            },
        },
    };

    const { instance } = await WebAssembly.instantiate(wasmBuffer, importObject);
    wasmExports = instance.exports as unknown as PcgWasmExports;

    // Initialize the emscripten runtime
    wasmExports.d();

    return wasmExports;
}

/** Create a new PCG32 RNG instance. Must be called after initPcgRng(). */
export function createPcgRng(seed?: number): PcgRng {
    if (!wasmExports) throw new Error('PCG WASM not initialized');

    const seedBig = BigInt(seed ?? Date.now());
    const seq = BigInt(1);
    const ptr = wasmExports.e(seedBig, seq);

    return {
        random(): number {
            return wasmExports!.h(ptr);
        },
        between(min: number, max: number): number {
            return wasmExports!.i(ptr, min, max, 1, 1);
        },
        destroy(): void {
            wasmExports!.f(ptr);
        },
    };
}

/** Load the WASM module. Call once at server startup. */
export async function initPcgRng(): Promise<void> {
    await loadWasm();
}
